pip install cycler
pip install kiwisolver
pip install matplotlib
pip install mpmath
pip install numpy
pip install Pillow
pip install pyparsing
pip install python_dateutil
pip install six
pip install sympy